# Generated by Django 4.2.7 on 2023-11-20 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[('SU', 'Simple_user'), ('SI', 'Singer'), ('PR', 'Producer'), ('MU', 'Musician'), ('SP', 'Supporter')], default='SU', max_length=2)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('f_name', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('l_name', models.CharField(max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('artist_name', models.CharField(max_length=30, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('status', models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر')),
                ('persentage', models.IntegerField(help_text='سهم موزیسین از فروش بیت بین 80 تا 100 درصد می باشد', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100)], verbose_name='سهم موزیسین')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('artist_name', models.CharField(max_length=30, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('status', models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر')),
                ('persentage', models.IntegerField(help_text='سهم پرودوسر از فروش بیت بین 80 تا 100 درصد می باشد', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100)], verbose_name='سهم پرودوسر')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('status', models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر')),
                ('artist_name', models.CharField(max_length=30, unique=True, verbose_name='نام هنری')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('Supporter_id', models.CharField(max_length=20, unique=True, verbose_name='آیدی پشتیبان')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
