# Generated by Django 4.2.7 on 2023-11-24 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_musician_persentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['status'], 'verbose_name': 'موزیسین', 'verbose_name_plural': 'موزیسین ها'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['status'], 'verbose_name': 'پرودوسر', 'verbose_name_plural': 'پرودوسر ها'},
        ),
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'verbose_name': 'کاربر ساده', 'verbose_name_plural': 'کاربران ساده'},
        ),
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['status'], 'verbose_name': 'خواننده', 'verbose_name_plural': 'خوانندگان'},
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['Supporter_id'], 'verbose_name': 'پشتیبان', 'verbose_name_plural': 'پشتیبان ها'},
        ),
        migrations.RemoveField(
            model_name='musician',
            name='status',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('OFL', 'Official'), ('UFL', 'Un_Official')], default='UFL', max_length=3, verbose_name='وضعیت کاربر'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='persentage',
            field=models.IntegerField(default=80, help_text='سهم پرودوسر از فروش بیت بین 80 تا 100 درصد می باشد', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(100)], verbose_name='سهم پرودوسر'),
        ),
    ]
