# Generated by Django 4.2.7 on 2023-11-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_musician_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر پروفایل')),
                ('f_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('l_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['supporter_id'], 'verbose_name': 'پشتیبان', 'verbose_name_plural': 'پشتیبان ها'},
        ),
        migrations.RemoveField(
            model_name='musician',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='Supporter_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='l_name',
        ),
        migrations.AddField(
            model_name='supporter',
            name='supporter_password',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='رمز عبور پشتیبان'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='supporter_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='آیدی پشتیبان'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.userprofile', verbose_name='پروفایل کاربر'),
        ),
    ]
