# Generated by Django 4.0.1 on 2023-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_alter_supporter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AddField(
            model_name='user',
            name='f_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='l_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
