# Generated by Django 4.2.7 on 2023-11-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
    ]
