# Generated by Django 4.2.7 on 2023-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('phone', models.IntegerField(verbose_name='شماره تلفن')),
                ('fullname', models.CharField(max_length=200, null=True, verbose_name='نام')),
                ('type', models.CharField(choices=[('SU', 'Simple_user'), ('SI', 'Singer'), ('PR', 'Producer'), ('MU', 'Musician'), ('SP', 'Supporter')], max_length=2, verbose_name='تایپ')),
                ('password', models.CharField(max_length=16, verbose_name='رمز عبور')),
                ('password_conf', models.CharField(max_length=16, verbose_name='رمز تایید شده')),
                ('otp', models.IntegerField(verbose_name='کد اعتبار سنجی')),
                ('expiration', models.DateTimeField(auto_now_add=True, verbose_name='زمان اعتبار سنجی')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
            ],
            options={
                'ordering': ['phone'],
            },
        ),
    ]
