# Generated by Django 4.2.7 on 2023-12-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_otp_options_remove_musician_artist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('musician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.musician')),
            ],
            options={
                'verbose_name': 'پروفایل موزیسین',
                'verbose_name_plural': 'پروفایل موزیسین ها',
            },
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.producer')),
            ],
            options={
                'verbose_name': 'پروفایل پرودوسر',
                'verbose_name_plural': 'پروفایل پرودوسرها',
            },
        ),
        migrations.CreateModel(
            name='SimpleUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.simpleuser')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.CreateModel(
            name='SingerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistic_name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='نام هنری')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='singer/image/profile/', verbose_name='تصویر پروفایل')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل کاربر')),
                ('singer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.singer')),
            ],
            options={
                'verbose_name': 'پروفایل خواننده',
                'verbose_name_plural': 'پروفایل خوانندگان',
            },
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expiration',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
