# Generated by Django 4.0.1 on 2023-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bits.Tag', verbose_name='برچسب ها'),
        ),
    ]
