# Generated by Django 4.2.7 on 2023-11-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bits.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='bit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bits.tag', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='bit',
            name='bpm',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bit',
            name='keys',
            field=models.CharField(max_length=20),
        ),
    ]
