# Generated by Django 4.2.7 on 2023-11-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_musician_options_alter_producer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ دسته بندی')),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='تصویر دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برچسب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ برچسب')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان ترک')),
                ('file', models.FileField(unique=True, upload_to='music/', verbose_name='فایل موزیک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات ترک')),
                ('release_date', models.DateField(verbose_name='تایم ریلیز شدن ترک')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='اضاقه شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.category', verbose_name='دسته بندی')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_traks', to='account.producer', verbose_name='پرودوسر')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_tracks', to='account.singer', verbose_name='خواننده')),
                ('tags', models.ManyToManyField(blank=True, to='tracks.tag', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'ترک',
                'verbose_name_plural': 'ترک ها',
                'ordering': ['created'],
            },
        ),
    ]
