# Generated by Django 4.0.1 on 2023-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tracks.Tag', verbose_name='برچسب ها'),
        ),
    ]
